apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fwd
  labels:
    app: nginx
spec:
  replicas: 5
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 25%
           maxUnavailable: 25%  
  selector:
    matchLabels:
      app: nginx-fwd
  template:
    metadata:
      labels:
        app: nginx-fwd
    spec:
      containers:
      - name: nginx
        image: hinata/nginx-forward-proxy
        ports:
        - containerPort: 3128
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - sleep 10 && curl ifconfig.me
        livenessProbe:
          httpGet:
            host: 10.1.0.152
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3